"""empty message

Revision ID: 26dba2ff3e74
Revises: 507852b6b55b
Create Date: 2014-12-09 00:48:19.112897

"""

# revision identifiers, used by Alembic.
revision = '26dba2ff3e74'
down_revision = '507852b6b55b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('social_id', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_user_social_id'), 'user', ['social_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_social_id'), table_name='user')
    op.drop_column('user', 'social_id')
    ### end Alembic commands ###
