"""empty message

Revision ID: 37c982fbe3f3
Revises: None
Create Date: 2014-11-20 20:12:17.526842

"""

# revision identifiers, used by Alembic.
revision = '37c982fbe3f3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
